name:                aoc19
version:             0.1.0.0
github:              "mvaldesdeleon/aoc19"
license:             BSD3
author:              "Martin Valdes de Leon"
maintainer:          "m.valdesdeleon@gmail.com"
copyright:           "Copyright (c) 2019 Martin Valdes de Leon"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- inputs/*.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mvaldesdeleon/aoc19#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- vector
- containers
- lens
- listsafe
- monad-loops
- parsec
- ListZipper

ghc-options:
#- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions: []

library:
  source-dirs: src
  generated-other-modules: Paths_aoc19

executables:
  day1:
    main:                Day1Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day1Main
    - -O2
    dependencies:
    - aoc19
    other-modules:
    - Paths_aoc19

  day2:
    main:                Day2Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day2Main
    - -O2
    dependencies:
    - aoc19
    other-modules:
    - Paths_aoc19

  day3:
    main:                Day3Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day3Main
    - -O2
    dependencies:
    - aoc19
    other-modules:
    - Paths_aoc19

tests:
  aoc19-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc19
